spring:
  application:
    name: eureka-service
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
     preferIpAddress: true
     instance:
       instance-id: ${spring-application.name}:${spring.cloud.client.ip-address}:${server.prot}
  server:
    enable-self-preservation: true