spring:
  application:
    name: eureka-server-slaveOne
  security:
    user:
      name: admin
      password: 123456
  profiles:
    active: slaveone
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false