spring:
  application:
    name: eureka-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    username: medicine
    server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
     preferIpAddress: true
     instance:
       instance-id: ${spring-application.name}:${spring.cloud.client.ip-address}:${server.prot}
  server:
    enable-self-preservation: true
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
