server:
  port: 8091
spring:
  application:
    name: user-hello
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG